# Generated by Django 4.0.3 on 2023-10-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sensor_uuid', models.CharField(max_length=256)),
                ('value', models.FloatField()),
                ('origin_value', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('sensor_uuid', 'timestamp')},
                'index_together': {('sensor_uuid', 'timestamp')},
            },
        ),
    ]
