version: "3.7"
services:

  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'

  postgis:
    image: 'postgis/postgis'
    ports:
      - '5454:5432'
    environment:
      POSTGRES_PASSWORD: welcome